name: StandardRB

on: [push, pull_request]

jobs:
  standardrb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0  # Update to your Ruby version
      - run: bundle install
      - run: bundle exec standardrb
